name: checkers
version: 0.1.0.0
dependencies:
- base >= 4.7 && < 5
- HUnit
- random
- entropy
- bytestring
- containers
- scotty
- http-types

executables:
  my-executable:
    main: Main.hs
    source-dirs: src